### ISSUE TITLE
Remove GH Action for Rancher 2.7

### ISSUE THREAD

**Issue by valaparthvi** [rancher-sandbox/rancher-turtles-e2e#18]
Rancher Turtles is not supported on Rancher 2.7 so that related job can be removed.
- [ ] Remove ui-rm_head_2.7.yaml
- [ ] Remove any specific steps added to the tests for RM 2.7.

**Comment by cpinjani** [comment]
Closing as completed via https://github.com/rancher-sandbox/rancher-turtles-e2e/pull/21
